[package]
name = "fm-render-term"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
fm-core.workspace = true
fm-layout.workspace = true

[dev-dependencies]
proptest = "1.6.0"
