[package]
name = "fm-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
fm-core.workspace = true
fm-layout.workspace = true
fm-parser.workspace = true
fm-render-svg.workspace = true
